---
- name: Configure the nodejs APT key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes

- name: Add nodejs repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_8.x xenial main'
    update_cache: yes
  become: yes

- name: Install nodejs 8.x
  apt: name=nodejs
  become: yes
