---
- name: restart redis-server
  service: name=redis-server state=restarted
  become: yes

- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted
  become: yes

- name: restart nginx
  service: name=nginx state=restarted
  become: yes