app_name: test
linux_user: test
linux_user_group: www-data

angular_server: True
react_server: True

app_dir: "/home/{{ linux_user }}/{{ app_name }}"
backend_app_dir: "{{ app_dir }}/backend"
angular_app_dir: "{{ app_dir }}/frontend/angular-app"
react_app_dir: "{{ app_dir }}/frontend/react-app"

# Git configuration
git_repo: git@github.com:Mohammed-Aadil/ansible-django-react-angular-setup.git

app_settings: backend.settings
app_wsgi_module: backend.wsgi

# Database configurations
db_setup: True  # for prod don't setup db use rds instead
db_name: "{{ app_name }}"
db_master_user: postgres
db_master_user_password:
db_user: db_user
db_user_password:
db_host:
db_port: 5432
database_url: "psql://{{ db_user }}:{{ db_user_password }}@{{ db_host }}:{{ db_port }}/{{ db_name }}"

# Python virtualenv configurations
venv_dir: '/home/{{ linux_user }}/envs/{{ app_name }}'
venv_python: '{{ venv_dir }}/bin/python3.6'