---
- name: Root custom promt on logging
  become: yes
  lineinfile:
    path: ~/.profile
    line: export {{ console_promt }}

- name: Root bash profile
  become: yes
  lineinfile:
    path: ~/.bashrc
    line: export {{ console_promt }}
  
- name: Creating project user
  user: name={{ linux_user }} groups={{ linux_user_group }} append=yes
  become: yes

- name: User custom promt on logging
  become: yes
  lineinfile:
    path: /home/{{ linux_user }}/.profile
    line: export {{ console_promt }}

- name: User bash profile
  become: yes
  lineinfile:
    path: /home/{{ linux_user }}/.bashrc
    line: export {{ console_promt }}

- name: Add deployer user to same group
  user: name={{ ansible_user_id }} groups={{ linux_user_group }} append=yes
  become: yes