---
- name: Ensure a locale exists
  locale_gen: name=en_US.UTF-8 state=present

- name: Ensure LANG is set to linux user
  become: yes
  lineinfile:
    path: /home/{{ linux_user }}/.bashrc
    line: "{{item}}"
  with_items:
    - "export LC_ALL=en_US.UTF-8"
    - "export LANG=en_US.UTF-8"
    - "export LANGUAGE=en_US.UTF-8"

- name: Ensure LANG is set to root user
  become: yes
  lineinfile:
    path: /root/.bashrc
    line: "{{item}}"
  with_items:
    - "export LC_ALL=en_US.UTF-8"
    - "export LANG=en_US.UTF-8"
    - "export LANGUAGE=en_US.UTF-8"
