---
- name: Install web client packages
  command: npm install
  args:
    chdir: "{{ angular_app_dir }}"

- name: Create .env file
  template:
    src: "env.j2"
    dest: "{{ angular_app_dir }}/.env"

- name: Build web client
  command: npm run build:prod
  args:
    chdir: "{{ angular_app_dir }}"
