git_branch: staging

# DNS configurations
domain: localhost

# django config
debug_mode: False

secret_key: sdlgbdfkjgb94ibrego493gtbhr3iuvfwg944tre
allowed_hosts: 127.0.0.1

default_superuser_email: admin@admin.com
default_superuser_password: 1qaz2wsx3

# Database configurations
db_user_password: 12345678
db_host: '127.0.0.1'

raven_dsn:

# Console customization
console_promt: PS1="\[\033[01;32m\]\u@staging \[\033[01;34m\]\t \w \$ \[\033[00m\]"

https: True  # If server configuration is https
ssl_certificate_path: /etc/letsencrypt/live/solastis.com/fullchain.pem
ssl_certificate_key_path: /etc/letsencrypt/live/solastis.com/privkey.pem

# cors settings
cors_disabled: True
cors_allowed_hosts: 127.0.0.1, localhost

web_client_backend_url: http://localhost:8000